const {Schema, model} = require('mongoose');
const brankasSchema = new Schema({
    _id: Schema.Types.ObjectId,
    axe: String,
    ayampotong: String,
    baju: String,
    batu: String,
    benang: String,
    buluayam: String,
    diamond: String,
    dompet: String,
    gold: String,
    iron: String,
    kain: String,
    kemasanayam: String,
    mapdokumen: String,
    obatstress: String,
    pecahanbatu: String,
    perban: String,
    phone: String,
    radio: String,
    sakuratea: String,
    skateboard: String,
    tembaga: String,
    udon: String,
    advancedlockpick: String,
    alumunium: String,
    joint: String,
    kecubung: String,
    lockpick: String,
    meth: String,
    olahankecubung: String,
    paketmeth: String,
    toolkitsenjata: String,
    vest: String,
    ak47: String,
    de: String,
    heavysniper: String,
    knife: String,
    machete: String,
    minismg: String,
    python: String,
    tech9: String,
    pelurumagnum: String,
    peluruacp: String,
    peluruae: String,
    pelurubmg: String,
    pelurulimalimaenam: String,
    pelurusembilanmm: String,
})

module.exports = model('Brankas',brankasSchema , "brankas");